<?php

/**
 * classification alphabetically in English
*/

return [
  
  'af-ZA'         =>  array( 'English'  => 'Afrikaans (South Africa)',                          'native' => 'Afrikaans (Suid-Afrika)'),
  'sq-AL'         =>  array( 'English'  => 'Albanian (Albania)',                                'native' => 'Shqip (Shqipëria)'),
  'gsw-FR'        =>  array( 'English'  => 'Alsatian (France)',                                 'native' => 'Elsässisch (Frànkrisch)'),
  'am-ET'         =>  array( 'English'  => 'Amharic (Ethiopia)',                                'native' => 'አማርኛ (ኢትዮጵያ)'),
  'ar'            =>  array( 'English'  => 'Arabic',                                            'native' => 'عربي'),
  'ar-DZ'         =>  array( 'English'  => 'Arabic (Algeria)',                                  'native' => 'العربية (الجزائر)'),
  'ar-BH'         =>  array( 'English'  => 'Arabic (Bahrain)',                                  'native' => 'لعربية (البحرين)'),
  'ar-EG'         =>  array( 'English'  => 'Arabic (Egypt)',                                    'native' => 'العربية (مصر)'),
  'ar-IQ'         =>  array( 'English'  => 'Arabic (Iraq)',                                     'native' => 'لعربية (العراق)'),
  'ar-JO'         =>  array( 'English'  => 'Arabic (Jordan)',                                   'native' => 'لعربية (الأردن)'),
  'ar-KW'         =>  array( 'English'  => 'Arabic (Kuwait)',                                   'native' => 'لعربية (الكويت)'),
  'ar-LB'         =>  array( 'English'  => 'Arabic (Lebanon)',                                  'native' => 'العربية (لبنان)'),
  'ar-LY'         =>  array( 'English'  => 'Arabic (Libya)',                                    'native' => 'العربية (ليبيا)'),
  'ar-MA'         =>  array( 'English'  => 'Arabic (Morocco)',                                  'native' => 'العربية (المملكة المغربية)'),
  'ar-OM'         =>  array( 'English'  => 'Arabic (Oman)',                                     'native' => 'العربية (عمان)'),
  'ar-QA'         =>  array( 'English'  => 'Arabic (Qatar)',                                    'native' => 'العربية (قطر)'),
  'ar-SA'         =>  array( 'English'  => 'Arabic (Saudi Arabia)',                             'native' => 'العربية (المملكة العربية السعودية)'),
  'ar-SY'         =>  array( 'English'  => 'Arabic (Syria)',                                    'native' => 'العربية (سوريا)'),
  'ar-TN'         =>  array( 'English'  => 'Arabic (Tunisia)',                                  'native' => 'العربية (تونس)'),
  'ar-AE'         =>  array( 'English'  => 'Arabic (U.A.E.)',                                   'native' => 'العربية (الإمارات العربية المتحدة)'),
  'ar-YE'         =>  array( 'English'  => 'Arabic (Yemen)',                                    'native' => 'العربية (اليمن)'),
  'hy-AM'         =>  array( 'English'  => 'Armenian (Armenia)',                                'native' => 'Հայերեն (Հայաստան)'),
  'as'            =>  array( 'English'  => 'Assamese (India)',                                  'native' => 'অসমীয়া'),
  'az-Cyrl-AZ'    =>  array( 'English'  => 'Azerbaijani (Cyrillic, Azerbaijan)',                'native' => 'Азәрбајҹан (Азәрбајҹан)'),
  'az-Latn-AZ'    =>  array( 'English'  => 'Azerbaijani (Latin, Azerbaijan)',                   'native' => 'Azərbaycan dili (Azərbaycan)'),
  'ba-RU'         =>  array( 'English'  => 'Bashkir (Russia)',                                  'native' => 'Башҡорт (Рәсәй)'),
  'eu-ES'         =>  array( 'English'  => 'Basque (Basque)',                                   'native' => 'euskara (euskara)'),
  'be-BY'         =>  array( 'English'  => 'Belarusian (Belarus)',                              'native' => 'Беларуская (Беларусь)'),
  'bn-BD'         =>  array( 'English'  => 'Bengali (Bangladesh)',                              'native' => 'বাংলা (বাংলাদেশ)'),
  'bn-IN'         =>  array( 'English'  => 'Bengali (India)',                                   'native' => 'বাংলা (ভারত)'),
  'bs-Cyrl-BA'    =>  array( 'English'  => 'Bosnian (Cyrillic, Bosnia and Herzegovina)',        'native' => 'босански (Босна и Херцеговина)'),
  'bs-Latn-BA'    =>  array( 'English'  => 'Bosnian (Latin, Bosnia and Herzegovina)',           'native' => 'bosanski (Bosna i Hercegovina)'),
  'br-FR'         =>  array( 'English'  => 'Breton (France)',                                   'native' => 'brezhoneg (Frañs)'),
  'bg-BG'         =>  array( 'English'  => 'Bulgarian (Bulgaria)',                              'native' => 'български (България)'),
  'my-MM'         =>  array( 'English'  => 'Burmese (Myanmar)',                                 'native' => 'ဗမာ (မြန်မာ)'),
  
  

  'ca'          => array( 'English' => 'Catalan',                   'native' => 'català'),
  'cs'          => array( 'English' => 'Czech',                     'native' => 'Čeština'),
  'cy'          => array( 'English' => 'Welsh',                     'native' => 'Cymraeg'),
  'da'          => array( 'English' => 'Danish',                    'native' => 'Dansk'),
  'de'          => array( 'English' => 'German',                    'native' => 'Deutsch'),
  'de-AT'       => array( 'English' => 'German (Austria)',          'native' => 'Deutsch (Österreich)'),
  'de-CH'       => array( 'English' => 'German (Switzerland)',      'native' => 'Deutsch (Schweiz)'),
  'de-DE'       => array( 'English' => 'German (Germany)',          'native' => 'Deutsch (Deutschland)'),
  'dsb'         => array( 'English' => 'Lower Sorbian',             'native' => 'Dolnoserbšćina'), // iso-639-2
  'el'          => array( 'English' => 'Greek',                     'native' => 'Ελληνικά'),
  'en-AU'       => array( 'English' => 'English (Australian)',      'native' => 'English (Australian)'),
  'en-CA'       => array( 'English' => 'English (Canadian)',        'native' => 'English (Canadian)'),
  'en-GB'       => array( 'English' => 'English (British)',         'native' => 'English (British)'),
  'en-NZ'       => array( 'English' => 'English (New Zealand)',     'native' => 'English (New Zealand)'),
  'en-US'       => array( 'English' => 'English (US)',              'native' => 'English (US)'),
  'en-ZA'       => array( 'English' => 'English (South African)',   'native' => 'English (South African)'),
  'eo'          => array( 'English' => 'Esperanto',                 'native' => 'Esperanto'),
  'es'          => array( 'English' => 'Spanish',                   'native' => 'Español'),
  'es-AR'       => array( 'English' => 'Spanish (Argentina)',       'native' => 'Español (de Argentina)'),
  'es-CL'       => array( 'English' => 'Spanish (Chile)',           'native' => 'Español (de Chile)'),
  'es-CO'       => array( 'English' => 'Spanish (Colombia)',        'native' => 'Español (de Colombia)'),
  'es-ES'       => array( 'English' => 'Spanish (Spain)',           'native' => 'Español (de España)'),
  'es-MX'       => array( 'English' => 'Spanish (Mexico)',          'native' => 'Español (de México)'),
  'et'          => array( 'English' => 'Estonian',                  'native' => 'Eesti keel'),
  'eu'          => array( 'English' => 'Basque',                    'native' => 'Euskara'),
  'fa'          => array( 'English' => 'Persian',                   'native' => 'فارسی'),
  'fi'          => array( 'English' => 'Finnish',                   'native' => 'suomi'),
  'fj-FJ'       => array( 'English' => 'Fijian',                    'native' => 'Vosa vaka-Viti'),
  'fr'          => array( 'English' => 'French',                    'native' => 'Français'),
  'fur-IT'      => array( 'English' => 'Friulian',                  'native' => 'Furlan'),
  'fy-NL'       => array( 'English' => 'Frisian',                   'native' => 'Frysk'),
  'ga'          => array( 'English' => 'Irish',                     'native' => 'Gaeilge'),
  'ga-IE'       => array( 'English' => 'Irish (Ireland)',           'native' => 'Gaeilge (Éire)'),
  'gd'          => array( 'English' => 'Gaelic (Scotland)',         'native' => 'Gàidhlig'),
  'gl'          => array( 'English' => 'Galician',                  'native' => 'Galego'),
  'gsw-FR'       => array( 'English' => 'Alsatian (France)',                  'native' => 'Elsässisch (Frànkrisch)'),
  'gu-IN'       => array( 'English' => 'Gujarati',                  'native' => 'ગુજરાતી'),
  'he'          => array( 'English' => 'Hebrew',                    'native' => 'עברית'),
  'hi'          => array( 'English' => 'Hindi',                     'native' => 'हिन्दी'),
  'hi-IN'       => array( 'English' => 'Hindi (India)',             'native' => 'हिन्दी (भारत)'),
  'hr'          => array( 'English' => 'Croatian',                  'native' => 'Hrvatski'),
  'hsb'         => array( 'English' => 'Upper Sorbian',             'native' => 'Hornjoserbsce'),
  'hu'          => array( 'English' => 'Hungarian',                 'native' => 'Magyar'),
  'hy-AM'       => array( 'English' => 'Armenian',                  'native' => 'Հայերեն'),
  'id'          => array( 'English' => 'Indonesian',                'native' => 'Bahasa Indonesia'),
  'is'          => array( 'English' => 'Icelandic',                 'native' => 'íslenska'),
  'it'          => array( 'English' => 'Italian',                   'native' => 'Italiano'),
  'ja'          => array( 'English' => 'Japanese',                  'native' => '日本語'),
  'ja-JP-mac'   => array( 'English' => 'Japanese',                  'native' => '日本語'), // not iso-639-1
  'ka'          => array( 'English' => 'Georgian',                  'native' => 'ქართული'),
  'kk'          => array( 'English' => 'Kazakh',                    'native' => 'Қазақ'),
  'kn'          => array( 'English' => 'Kannada',                   'native' => 'ಕನ್ನಡ'),
  'ko'          => array( 'English' => 'Korean',                    'native' => '한국어'),
  'ku'          => array( 'English' => 'Kurdish',                   'native' => 'Kurdî'),
  'la'          => array( 'English' => 'Latin',                     'native' => 'Latina'),
  'lg'          => array( 'English' => 'Luganda',                   'native' => 'Luganda'),
  'lt'          => array( 'English' => 'Lithuanian',                'native' => 'lietuvių kalba'),
  'lv'          => array( 'English' => 'Latvian',                   'native' => 'Latviešu'),
  'mai'         => array( 'English' => 'Maithili',                  'native' => 'मैथिली মৈথিলী'),
  'mg'          => array( 'English' => 'Malagasy',                  'native' => 'Malagasy'),
  'mi'          => array( 'English' => 'Maori (Aotearoa)',          'native' => 'Māori (Aotearoa)'),
  'mk'          => array( 'English' => 'Macedonian',                'native' => 'Македонски'),
  'ml'          => array( 'English' => 'Malayalam',                 'native' => 'മലയാളം'),
  'mn'          => array( 'English' => 'Mongolian',                 'native' => 'Монгол'),
  'mr'          => array( 'English' => 'Marathi',                   'native' => 'मराठी'),
  'nb-NO'       => array( 'English' => 'Norwegian (Bokmål)',        'native' => 'Norsk bokmål'),
  'ne-NP'       => array( 'English' => 'Nepali',                    'native' => 'नेपाली'),
  'nn-NO'       => array( 'English' => 'Norwegian (Nynorsk)',       'native' => 'Norsk nynorsk'),
  'nl'          => array( 'English' => 'Dutch',                     'native' => 'Nederlands'),
  'nr'          => array( 'English' => 'Ndebele, South',            'native' => 'isiNdebele'),
  'nso'         => array( 'English' => 'Northern Sotho',            'native' => 'Sepedi'),
  'oc'          => array( 'English' => 'Occitan (Lengadocian)',     'native' => 'occitan (lengadocian)'),
  'or'          => array( 'English' => 'Oriya',                     'native' => 'ଓଡ଼ିଆ'),
  'pa-IN'       => array( 'English' => 'Punjabi',                   'native' => 'ਪੰਜਾਬੀ'),
  'pl'          => array( 'English' => 'Polish',                    'native' => 'Polski'),
  'pt-BR'       => array( 'English' => 'Portuguese (Brazilian)',    'native' => 'Português (do Brasil)'),
  'pt-PT'       => array( 'English' => 'Portuguese (Portugal)',     'native' => 'Português (Europeu)'),
  'ro'          => array( 'English' => 'Romanian',                  'native' => 'română'),
  'rm'          => array( 'English' => 'Romansh',                   'native' => 'rumantsch'),
  'ru'          => array( 'English' => 'Russian',                   'native' => 'Русский'),
  'rw'          => array( 'English' => 'Kinyarwanda',               'native' => 'Ikinyarwanda'),
  'si'          => array( 'English' => 'Sinhala',                   'native' => 'සිංහල'),
  'sk'          => array( 'English' => 'Slovak',                    'native' => 'slovenčina'),
  'sl'          => array( 'English' => 'Slovenian',                 'native' => 'slovensko'),
  'son'         => array( 'English' => 'Songhai',                   'native' => 'Soŋay'),
  'sq-AL'          => array( 'English' => 'Albanian (Albania)',                  'native' => 'Shqip (Shqipëria)'),
  'sr'          => array( 'English' => 'Serbian',                   'native' => 'Српски'),
  'sr-Latn'     => array( 'English' => 'Serbian',                   'native' => 'Srpski'), // follows RFC 4646
  'ss'          => array( 'English' => 'Siswati',                   'native' => 'siSwati'),
  'st'          => array( 'English' => 'Southern Sotho',            'native' => 'Sesotho'),
  'sv-SE'       => array( 'English' => 'Swedish',                   'native' => 'Svenska'),
  'ta'          => array( 'English' => 'Tamil',                     'native' => 'தமிழ்'),
  'ta-IN'       => array( 'English' => 'Tamil (India)',             'native' => 'தமிழ் (இந்தியா)'),
  'ta-LK'       => array( 'English' => 'Tamil (Sri Lanka)',         'native' => 'தமிழ் (இலங்கை)'),
  'te'          => array( 'English' => 'Telugu',                    'native' => 'తెలుగు'),
  'th'          => array( 'English' => 'Thai',                      'native' => 'ไทย'),
  'tn'          => array( 'English' => 'Tswana',                    'native' => 'Setswana'),
  'tr'          => array( 'English' => 'Turkish',                   'native' => 'Türkçe'),
  'ts'          => array( 'English' => 'Tsonga',                    'native' => 'Xitsonga'),
  'tt-RU'       => array( 'English' => 'Tatar',                     'native' => 'Tatarça'),
  'uk'          => array( 'English' => 'Ukrainian',                 'native' => 'Українська'),
  'ur'          => array( 'English' => 'Urdu',                      'native' => 'اُردو'),
  've'          => array( 'English' => 'Venda',                     'native' => 'Tshivenḓa'),
  'vi'          => array( 'English' => 'Vietnamese',                'native' => 'Tiếng Việt'),
  'wo'          => array( 'English' => 'Wolof',                     'native' => 'Wolof'),
  'xh'          => array( 'English' => 'Xhosa',                     'native' => 'isiXhosa'),
  'zh-CN'       => array( 'English' => 'Chinese (Simplified)',      'native' => '中文 (简体)'),
  'zh-TW'       => array( 'English' => 'Chinese (Traditional)',     'native' => '正體中文 (繁體)'),
  'zu'          => array( 'English' => 'Zulu',                      'native' => 'isiZulu')

];
